// export var jigsawBackend = "http://localhost:7000";
export var jigsawBackend = "https://jigsaw-server.herokuapp.com";


export var issuerPublicKey = "GD5VAU3K6RQE5SUPNJADXMMYNXYQREO5YW334T23N43IHNPJT2DAPPME";


export var JIGXUIssuerPublicKey = "GAQBC7CWGI5N77IA2CUACSVJKGB5XZNDFML4RIAD4VOZAYXXIZ5ZDAQ2";
export var JIGXKIssuerPublicKey = "GCSQ475DWPDJAZABG5OHJDZ7OTP2SZQAYP5RHXPRLCCXKWPF3KN2PFAL";
export var JIGXUDistributorPublicKey = "GB2VSR3KAUKYOHXHXFTY2UZSJVVJSYS4OE5MKYWQVDGLVLMV5NGA33WH";

export var JIGXUPoolAccount = "GDZ2H4LHIKNFAPVAKJMHIGKRHBQYW5I3YTUNJ63ML5C7NDL3V3G5V6VX";

